### ISSUE TITLE
[FR] Option to add custom yaml fields that are unrelated to Zotero fields

### ISSUE THREAD

**Issue by FeralFlora** [PKM-er/obsidian-zotero#103]
I would like my Literature notes to have yaml fields such as `status` and `priority`. It would be nice if it was possible to add such custom fields to the literature notes through settings or as yaml fields in the zt-note.eta file. The yaml option doesn't work, and custom fields are currently ignored in the Mapping settings.

**Comment by bvorak** [comment]
I specifically would like to set an items title (and alternative citekeys) as aliases, that show up in the quickswitcher.

**Comment by MichaTarlton** [comment]
Vital feature. Also with #125 yaml customization features are needed. I do appreciate the how user-friendly the current approach is though.

**Comment by MSBack** [comment]
> I specifically would like to set an items title (and alternative citekeys) as aliases, that show up in the quickswitcher.

You can do that. Make a field using "title", and call it aliases.

**Comment by aidenlx** [comment]
Note Property now has a dedicated template in v1.1.0, make sure to check out [the document](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) on this changes and [cheatsheets](https://obzt.aidenlx.top/how-to/template-cheatsheet)
