### ISSUE TITLE
Feature: handle auto added tags from zotero

### ISSUE THREAD

**Issue by FeralFlora** [PKM-er/obsidian-zotero#106]
When putting `tags` as a mapped field to import into the yaml, only the manually added tags are imported.
This behavior seems like a bug, and if not, it is unpredictable and should be controllable by the user.

**Comment by aidenlx** [comment]
Tags imports filters are now customizable, you can now import tags from literature, in addition to manually added ones. Please check out the [documentation](http://localhost:3000/zh-CN/how-to/template-cheatsheet#only-manual-tags) for more details.
