### ISSUE TITLE
[FR] Option to configure Eta with autoTrim: false

### ISSUE THREAD

**Issue by FeralFlora** [PKM-er/obsidian-zotero#110]
From the Eta docs:
>By default, Eta removes the first newline character after each tag. This can be [configured](https://eta.js.org/docs/api/configuration)

This default behavior causes a lot of issues when templating. Or atleast, that's where I think the issues I'm having with whitespace control are coming from. I'm having issues with list items not being on separate lines without adding double spacing at the end of lines.

There are also issues with callouts, where blockquote symbols will end up at the end of a rendered tag like so:

`Publication: <% = it.publicationTitle %>` becomes `Publication: Journal of Environmental Psychology>`

Notice the `>` at the end.

**Comment by aidenlx** [comment]
yeah I agree that it's not so intuitive. I believe this is enabled in eta by default to allow placing long list of successive tags in multiple lines. I may toggle this off by default in future release
