### ISSUE TITLE
Feature: Custom format for date in frontmatter fields

### ISSUE THREAD

**Issue by zhechenghu** [PKM-er/obsidian-zotero#125]
Now date only supports the year form. And I want the m/d/y form or "yyyy-mm-dd" form to place the note in the correct order with the "project" plug-in.

I would appreciate it a lot if someone could tell me how.

**Comment by aidenlx** [comment]
date properties from Zotero sometimes do have only year, which is something I can't do anything about. However, in v1.1.0, you can choose how to parse it in Note Property template, make sure to check out [the document](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) on this changes and [cheatsheets](https://obzt.aidenlx.top/how-to/template-cheatsheet#date)
