### ISSUE TITLE
Remove "" for date in YAML

### ISSUE THREAD

**Issue by ming-cui** [PKM-er/obsidian-zotero#133]
By adding `date` onto Template Mapping section, .md note file will have `"year"`. Is it possible to remove `""` so that only the year number will be kept? Thank you!

**Comment by aidenlx** [comment]
In v1.1.0, you can choose how to parse it in Note Property template, Note Property now has a dedicated template in v1.1.0, make sure to check out [the document](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) on this changes and [cheatsheets](https://obzt.aidenlx.top/how-to/template-cheatsheet#date)
