### ISSUE TITLE
[BUG] Tabs (four spaces) get inserted into the yaml titles of articles

### ISSUE THREAD

**Issue by FeralFlora** [PKM-er/obsidian-zotero#139]
When importing a literature note, the titles get broken apart with a tab (four spaces) at around 69 characters (two examples, but also found one title that was cut off at 74 characters). Titles shorter than this don't appear to get broken up with spaces.

See screenshots:
![image](https://github.com/aidenlx/obsidian-zotero/assets/33608083/2442e28a-e16d-4ead-b18b-19c3203476b0)
![image](https://github.com/aidenlx/obsidian-zotero/assets/33608083/0153327f-b4c9-419b-8abb-27e2c1321a2a)

**Comment by aidenlx** [comment]
This is YAML prettifier trying to keep it readable in editor without auto line warp, which cannot be disabled in obsidian. They are all vaild yaml and should work as expected.

**Comment by FeralFlora** [comment]
> This is YAML prettifier trying to keep it readable in editor without auto line warp, which cannot be disabled in obsidian. They are all vaild yaml and should work as expected.

Couldn't you do some post-processing like replace consecutive spaces with a single one? Also, how come Zotero Integration doesn't face the same issue then? Do you have a link to Obsidian's yaml prettifier?
