### ISSUE TITLE
[BUG] Title formatting is inconsistent

### ISSUE THREAD

**Issue by FeralFlora** [PKM-er/obsidian-zotero#140]
Some titles are surrounded by "", whilst others are not. See the screenshots in https://github.com/aidenlx/obsidian-zotero/issues/139.

Both articles in this example are formatted the same in Zotero. The symbols are not present in Zotero in either case.

**Comment by aidenlx** [comment]
Same as #139, there isn't too much I can do about it. Also check out [here](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) to see why quote may be added
