### ISSUE TITLE
Feature: custom link format for page link drag-n-drop in annotation view

### ISSUE THREAD

**Issue by calmwaves111** [PKM-er/obsidian-zotero#141]
![image](https://github.com/aidenlx/obsidian-zotero/assets/56907077/b10e420f-abc6-4627-92aa-3c3af77cf0e0)
annotation can be dragged into the text box by dragging the icon in the upper left corner, and the format is defined by zt-anno (although it does not support it.title

【page 27】 can be dragged into the text box, but its format is fixed now, I hope it can be customized

it.title is important to me and I want it to be available in the zt-anno.eta

**Comment by aidenlx** [comment]
It's two dedicated issues: 
1. it.title in annotation
2. custom link format for page link drag-n-drop in annotation view

for first issue, use `it.docItem.title` to access title in `zt-annot.eta` template, see [here](https://obzt.aidenlx.top/zh-CN/getting-started/basic-usage/template-config#note-annot-template) for more details

the second issue will be tracked in #143
