### ISSUE TITLE
[Bug] it.comment adds a wikilink when using the drag from right sidebar.

### ISSUE THREAD

**Issue by ronny3** [PKM-er/obsidian-zotero#149]
When an annotation has a comment, it.comment adds `[content](content)` style link when dragging from the sidebar, but not when parsing the literature note.
This leads to not being able to drag multi-line comments, as it.commentMd squashes all lines into one.

How to reproduce:
Make an annotation with a comment.
Have `<%= it.commentMd %>` in zt-annot.eta.
Drag the annotation from the right sidebar, it will now be a link instead of just the content.

**Comment by aidenlx** [comment]
I can't reproduce this in v1.1.0 beta, could you upgrade to latest version and see if it presist?

**Comment by ronny3** [comment]
> I can't reproduce this in v1.1.0 beta, could you upgrade to latest version and see if it presist?

It works now. I can drag multi-line comments. Thx.
