### ISSUE TITLE
[QA] How to add "@citekey" as alias  to Literature note

### ISSUE THREAD

**Issue by anandkumar89** [PKM-er/obsidian-zotero#150]
Usecase: 

```
---
alias : @auth2023
---
```
refer `[@auth2023]` for further discussion. 

---

This will allow connections between nodes in graphs. But I'm not sure how to achieve this.

**Comment by anandkumar89** [comment]
current solution is to rename file as `@citekey` and manually add `alias` fields from side pane. But a native solution would be appreciated, e.g. `template for metadata` as in `citations` plugin

**Comment by anandkumar89** [comment]
Thanks, this is acceptable workaround till `frontmatter` is available as editable template.

**Comment by MSBack** [comment]
This would be useful if you don't have the citekey as the filename of the note. 

But why would you want an alias that is identical to the actual filename? In that case, it's not really actually an alias, and it is redundant.

Anyway, I second the last comment that it would be much more straightforward if the frontmatter was part of a template, rather than being set in the plugin's settings.

**Comment by InvisCat** [comment]
> > ... solution is to rename file as `@citekey` **and** manually add `alias` fields from side pane ...
> 
> My bad with incorrect use of "and", wanted @citekey as alias but ended up renaming filename as "@citekey" as can't add it as alias programatically. This is either or situation.
> 
> End goal is to be able to link to literature note [[link]] either by `title` or by `@citekey` in Obsidian.
> 
> The syntax "@citekey" could be useful if later would decide to parse a long .md file to latex other than fact that it ("@citekey") is prevalent syntax for citing within markdown community.
> 
> @aidenlx could **frontmatter as template** be a feasible feature request?

+1, I need this feature too

**Comment by aidenlx** [comment]
In v1.1.0-beta.0, you can use the following
```ejs
aliases: @<%= it.citekey =>
```

make sure to check out [the document](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) on this changes and [cheatsheets](https://obzt.aidenlx.top/how-to/template-cheatsheet#date)
