### ISSUE TITLE
[Bug] incorrect pdf file link generated when using ZotFile in Zotero

### ISSUE THREAD

**Issue by SeveNOlogy7** [PKM-er/obsidian-zotero#151]
First of all, a huge thank you for creating this plugin! 

## Description
ZotFile is a Zotero plugin that would move attached PDF in Zotero to a custom location. This operation would leave a link to that location in Zotero.
It seems that the obsidian-zotero plugin does not recognize the ZotFile 'link' and assumes that the PDF file is stored in Zotero\storage folder.

## To reproduce:
In Zotero, use ZotFile to move PDF to other location,
In Obsidian, use the default template to generate a literature note.
Click on the generate 'attachment' link.

## Screenshot
![image](https://github.com/aidenlx/obsidian-zotero/assets/7949424/9adc1630-5140-446f-bbb5-1443daf5f13c)

**Comment by tpulha** [comment]
Same issue here.

**Comment by jacobleft** [comment]
Same

**Comment by bepolymathe** [comment]
Yes i can confirm too.

**Comment by machado-t** [comment]
Is there any workaround for this?

**Comment by aidenlx** [comment]
Fixed in v1.1.0-beta.2

**Comment by Astro-Aionia** [comment]
There is still someting error, shown below (zotlit version 1.1.4). Does anybody know how to fix it?

![image](https://github.com/PKM-er/obsidian-zotlit/assets/83877315/276ba320-c277-428b-acb1-3d8f5d84e554)

**Comment by krzyfu** [comment]
I have the same problem: 
![image](https://github.com/PKM-er/obsidian-zotlit/assets/54978191/fa6c631f-fcd9-49cf-b902-9a45083143b2)
would be fantastic to fix it, finally...
