### ISSUE TITLE
The electron version of Obsidian is newer than the one supported by the plugin.

### ISSUE THREAD

**Issue by FelixBrakel** [PKM-er/obsidian-zotero#152]
When trying to enable the plugin after having installed it using the BRAT method I get the following error:

The electron (electron: 25.2.1, module version: 116) in current version of obsidian is newer than the one supported by installed obsidian-zotero-plugin, please update obsidian-zotero-plugin to latest version.

**Comment by FelixBrakel** [comment]
The same issue occurs when using the manual installation method

**Comment by aidenlx** [comment]
should be fixed now

**Comment by MichaBrugger** [comment]
Unfortunately got that same issue.

**Comment by FelixBrakel** [comment]
Are you using the manual installation method or the BRAT one? The BRAT method takes the master branch but the fix is on the dev branch. I think you can change the branch somehow?

**Comment by MichaBrugger** [comment]
I used BRAT, that explains the error. I will try if I can make BRAT use the dev branch and update you here once I figured. Thanks for the help already 👍🏼
