### ISSUE TITLE
FR: Add the 'date' field from Zotero annotation

### ISSUE THREAD

**Issue by ronny3** [PKM-er/obsidian-zotero#155]
Self-explanatory. Currently the date field is not available. It exists in Zotero annotations in a field named 'date'.

**Comment by aidenlx** [comment]
Note Property now has a dedicated template in v1.1.0, make sure to check out [the document](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) on this changes and [cheatsheets on dates](https://obzt.aidenlx.top/how-to/template-cheatsheet#date)

**Comment by ronny3** [comment]
@aidenlx hey, this did not concern this issue. Zotero has "date added" and "date modified" on its annotations. They are not available in the Item Data as seen from the data explorer.

**Comment by aidenlx** [comment]
Sorry, too many replies at once, check out beta3 to see if those fields work as expect :)

**Comment by ronny3** [comment]
> Sorry, too many replies at once, check out beta3 to see if those fields work as expect :)

Thanks, they do indeed!
